### ISSUE TITLE
pretrained models?

### ISSUE THREAD

**Issue by tumble-weed** [tmllab/PICMM#1]
hello,
will you be releasing your pretrained models?

**Comment by xiaoboxia** [comment]
Our code has been made publicly available, and you can run it following the steps provided in the README. We have implemented a lightweight network model for image completion in our paper, which, under the configuration of a single V100/A100/3090, is capable of quickly obtaining high-quality models on datasets such as Celeba-HQ, StreetView, and Places2. Thank you for your interest, and we hope our work can be of help to you.
