### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by tumble-weed** [tmllab/PICMM#2]
hello,
how much time does pluralistic inference take? is sampling from the GMM costly?

**Comment by xiaoboxia** [comment]
Regarding the time required for pluralistic inference, we have conducted detailed experiments. Results are presented in Table 4 of our paper. The experimental results show that for inferring 100 images, our method takes approximately 14 seconds to generate 6 diverse completion images, demonstrating high efficiency. Thank you for your inquiry. We hope this provides useful information for you.
